//! Settings schema path validation.
//!
//! Validates that every `path` field in the JSON settings UI schemas
//! corresponds to a real config field in the Rust struct definitions.
//! This catches drift when Rust struct fields are renamed or removed
//! but the corresponding UI JSON files aren't updated.
//!
//! # How it works
//!
//! 1. Serialize `schemars::schema_for!()` for both `AppConfig` and
//!    `AgentConfig` to JSON values, then merge them into a single
//!    combined schema so the tree walker can validate paths against
//!    either struct.
//! 2. Walk the UI JSON tree recursively, tracking a "type context" that
//!    starts at the merged schema.
//! 3. When entering a `collection` node, resolve the collection's path
//!    against the current type context and switch to the item type.
//! 4. When encountering a `field` node, validate its `path` is a known
//!    field in the current type context.
//! 5. All errors are collected and reported together.

use serde_json::Value;

use crate::agentjax_err;
use crate::error::AgentJaxResult;

// ── Public API ─────────────────────────────────────────────────────────────

/// Validate all `path` fields in the given settings sections against the
/// Rust config type schemas (generated by `schemars`).
///
/// Paths are validated against a merged schema that includes fields from
/// both `AppConfig` (shared config) and `AgentConfig` (per-agent config),
/// since settings UI sections reference fields from both.
pub fn validate_settings_paths(sections: &[Value]) -> AgentJaxResult<()> {
    let merged_schema = build_merged_config_schema();
    let mut errors: Vec<String> = Vec::new();

    for section in sections {
        let section_id = section
            .get("id")
            .and_then(Value::as_str)
            .unwrap_or("<unknown>");
        if let Err(section_errors) = validate_node(section, &merged_schema, &merged_schema, "") {
            let joined = section_errors.join("; ");
            errors.push(format!("section \"{section_id}\": {joined}"));
        }
    }

    if errors.is_empty() {
        Ok(())
    } else {
        let msg = format!(
            "Settings schema path validation failed:\n{}",
            errors.join("\n")
        );
        Err(agentjax_err!(msg, Config))
    }
}

// ── Schema loading ─────────────────────────────────────────────────────────

/// Build a combined schema that includes properties from both `AppConfig`
/// and `AgentConfig`, so the validator can check paths against either.
fn build_merged_config_schema() -> Value {
    let app_schema = schemars::schema_for!(super::AppConfig);
    let agent_schema = schemars::schema_for!(super::agent_config::AgentConfig);

    let app_value: Value = serde_json::to_value(&app_schema)
        .expect("AppConfig schemars schema must serialise to JSON");
    let agent_value: Value = serde_json::to_value(&agent_schema)
        .expect("AgentConfig schemars schema must serialise to JSON");

    merge_properties(app_value, agent_value)
}

/// Merge two schemars JSON schemas into one, combining `properties`, `$defs`,
/// and `required` arrays from both.
///
/// The `base` schema's values are kept when there's a conflict in `properties`
/// or `$defs`; the `overlay` fills in any keys not already present.
fn merge_properties(mut base: Value, overlay: Value) -> Value {
    if let Some(base_obj) = base.as_object_mut() {
        if let Some(overlay_obj) = overlay.as_object() {
            // Merge the `properties` maps
            merge_object_maps(base_obj, overlay_obj, "properties");

            // Merge the `$defs` maps (type definitions referenced by $ref)
            merge_object_maps(base_obj, overlay_obj, "$defs");

            // Merge `required` arrays
            if let Some(base_req) = base_obj.get_mut("required").and_then(|r| r.as_array_mut()) {
                if let Some(overlay_req) = overlay_obj.get("required").and_then(|r| r.as_array()) {
                    for val in overlay_req {
                        if !base_req.contains(val) {
                            base_req.push(val.clone());
                        }
                    }
                }
            }
        }
    }
    base
}

/// Helper: for a given key (e.g. "properties" or "$defs"), merge the
/// overlay's object entries into the base's object, skipping duplicates.
fn merge_object_maps(
    base_obj: &mut serde_json::Map<String, Value>,
    overlay_obj: &serde_json::Map<String, Value>,
    key: &str,
) {
    if let Some(base_map) = base_obj.get_mut(key).and_then(|m| m.as_object_mut()) {
        if let Some(overlay_map) = overlay_obj.get(key).and_then(|m| m.as_object()) {
            for (k, v) in overlay_map {
                if !base_map.contains_key(k) {
                    base_map.insert(k.clone(), v.clone());
                }
            }
        }
    } else if let Some(overlay_map) = overlay_obj.get(key).and_then(|m| m.as_object()) {
        base_obj.insert(key.to_string(), Value::Object(overlay_map.clone()));
    }
}

/// Build the merged AppConfig + AgentConfig schema for path validation.
/// Public so that `path_registry.rs` and other modules can use it.
pub fn build_merged_schema() -> Value {
    build_merged_config_schema()
}

// ── Tree walker ────────────────────────────────────────────────────────────

fn validate_node(
    node: &Value,
    root_schema: &Value,
    ctx_schema: &Value,
    ctx_desc: &str,
) -> Result<(), Vec<String>> {
    let mut errors: Vec<String> = Vec::new();

    let kind = node.get("kind").and_then(Value::as_str);

    match kind {
        Some("field") => {
            if let Some(path) = node.get("path").and_then(Value::as_str) {
                let node_id = node.get("id").and_then(Value::as_str).unwrap_or("<no id>");
                if let Err(path_errors) = validate_field_path(path, ctx_schema, root_schema) {
                    for err in path_errors {
                        errors.push(format!(
                            "  field \"{node_id}\" path=\"{path}\" in {ctx_desc}: {err}"
                        ));
                    }
                }
            }
        }

        Some("collection") => {
            if let Some(collection_path) = node.get("path").and_then(Value::as_str) {
                let node_id = node.get("id").and_then(Value::as_str).unwrap_or("<no id>");

                match resolve_collection_item_schema(collection_path, ctx_schema, root_schema) {
                    Ok(item_schema) => {
                        let new_ctx = if ctx_desc.is_empty() {
                            format!("collection \"{collection_path}\"")
                        } else {
                            format!("{ctx_desc}.{collection_path}")
                        };
                        if let Some(children) = node.get("children").and_then(Value::as_array) {
                            for child in children {
                                if let Err(child_errors) =
                                    validate_node(child, root_schema, &item_schema, &new_ctx)
                                {
                                    errors.extend(child_errors);
                                }
                            }
                        }
                        return if errors.is_empty() {
                            Ok(())
                        } else {
                            Err(errors)
                        };
                    }
                    Err(msg) => {
                        errors.push(format!(
                            "  collection \"{node_id}\" path=\"{collection_path}\" in {ctx_desc}: {msg}"
                        ));
                    }
                }
            }
        }

        _ => {}
    }

    // Recurse into children
    if let Some(children) = node.get("children").and_then(Value::as_array) {
        for child in children {
            if let Err(child_errors) = validate_node(child, root_schema, ctx_schema, ctx_desc) {
                errors.extend(child_errors);
            }
        }
    }

    // Recurse into tabs
    if let Some(tabs) = node.get("tabs").and_then(Value::as_array) {
        for tab in tabs {
            if let Some(tab_children) = tab.get("children").and_then(Value::as_array) {
                for child in tab_children {
                    if let Err(child_errors) =
                        validate_node(child, root_schema, ctx_schema, ctx_desc)
                    {
                        errors.extend(child_errors);
                    }
                }
            }
        }
    }

    // Recurse into itemTemplate
    if let Some(template) = node.get("itemTemplate") {
        if let Err(template_errors) = validate_node(template, root_schema, ctx_schema, ctx_desc) {
            errors.extend(template_errors);
        }
    }

    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors)
    }
}

// ── Field path validation ──────────────────────────────────────────────────

fn validate_field_path(
    path: &str,
    ctx_schema: &Value,
    root_schema: &Value,
) -> Result<(), Vec<String>> {
    let segments: Vec<&str> = path.split('.').collect();
    let mut errors = Vec::new();
    let mut current = ctx_schema;
    let empty_obj = Value::Object(Default::default());

    for (i, segment) in segments.iter().enumerate() {
        // schema_for!() serialized to JSON produces properties at the top level
        current = follow_ref(current, root_schema);

        // Check properties (schemars puts them at root level: schema.properties)
        let has_properties = current
            .get("properties")
            .and_then(|p| p.as_object())
            .map(|props| props.contains_key(*segment))
            .unwrap_or(false);

        if has_properties {
            // Move into the property's schema for the next segment
            let props = current
                .get("properties")
                .and_then(|p| p.as_object())
                .unwrap();
            current = props.get(*segment).unwrap();
            continue;
        }

        // Check additionalProperties (BTreeMap / maps)
        if let Some(additional) = current.get("additionalProperties") {
            match additional {
                Value::Bool(true) => {
                    current = &empty_obj;
                    continue;
                }
                Value::Bool(false) => {}
                _ => {
                    current = follow_ref(additional, root_schema);
                    continue;
                }
            }
        }

        errors.push(format!(
            "segment \"{segment}\" not found in schema (path=\"{path}\", i={i})"
        ));
        return Err(errors);
    }

    Ok(())
}

// ── Collection path resolution ─────────────────────────────────────────────

fn resolve_collection_item_schema(
    path: &str,
    ctx_schema: &Value,
    root_schema: &Value,
) -> Result<Value, String> {
    let segments: Vec<&str> = path.split('.').collect();
    if segments.is_empty() {
        return Err("empty path".into());
    }

    let mut current = ctx_schema.clone();
    let last_idx = segments.len() - 1;

    for (i, segment) in segments.iter().enumerate() {
        if i < last_idx {
            let resolved = resolve_schema_property(&current, segment, root_schema)
                .map_err(|e| format!("segment \"{segment}\": {e}"))?;
            current = resolved.clone();
        } else {
            // Last segment: resolve to find the collection item type
            let resolved = resolve_schema_property(&current, segment, root_schema)
                .map_err(|e| format!("last segment \"{segment}\": {e}"))?;

            // The property's schema might be a $ref or have additionalProperties
            let resolved = follow_ref(resolved, root_schema);

            if let Some(additional) = resolved.get("additionalProperties") {
                if !matches!(additional, Value::Bool(false)) {
                    return Ok(follow_ref(additional, root_schema).clone());
                }
            }

            // Some BTreeMap types have `type: object` + `additionalProperties`
            // without being wrapped in a `$ref` — check the resolved schema itself
            if resolved.get("type").and_then(Value::as_str) == Some("object") {
                if let Some(properties) = resolved.get("properties") {
                    if let Some(prop_val) = properties.get(*segment) {
                        let prop_resolved = follow_ref(prop_val, root_schema);
                        if let Some(additional) = prop_resolved.get("additionalProperties") {
                            if !matches!(additional, Value::Bool(false)) {
                                return Ok(follow_ref(additional, root_schema).clone());
                            }
                        }
                    }
                }
            }

            return Err(format!(
                "\"{segment}\" is not a map type (no additionalProperties)"
            ));
        }
    }

    Err("empty path".into())
}

// ── Helpers ────────────────────────────────────────────────────────────────

pub(crate) fn follow_ref<'a>(schema: &'a Value, root_schema: &'a Value) -> &'a Value {
    if let Some(ref_str) = schema.get("$ref").and_then(Value::as_str) {
        if let Some(def_path) = ref_str.strip_prefix("#/$defs/") {
            if let Some(defs) = root_schema.get("$defs").and_then(|d| d.as_object()) {
                if let Some(def_schema) = defs.get(def_path) {
                    return follow_ref(def_schema, root_schema);
                }
            }
        }
    }
    schema
}

pub(crate) fn resolve_schema_property<'a>(
    schema: &'a Value,
    segment: &str,
    root_schema: &'a Value,
) -> Result<&'a Value, String> {
    let resolved = follow_ref(schema, root_schema);

    if let Some(properties) = resolved.get("properties").and_then(|p| p.as_object()) {
        if let Some(prop_schema) = properties.get(segment) {
            return Ok(prop_schema);
        }
    }

    if let Some(additional) = resolved.get("additionalProperties") {
        if !matches!(additional, Value::Bool(false)) {
            return Ok(additional);
        }
    }

    Err(format!("no property \"{segment}\" found"))
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// Returns the merged AppConfig + AgentConfig schema for validation.
    fn merged_schema() -> Value {
        build_merged_config_schema()
    }

    fn def(schema: &Value, name: &str) -> Value {
        schema
            .get("$defs")
            .and_then(|d| d.get(name))
            .cloned()
            .unwrap_or_else(|| panic!("{name} not found in $defs"))
    }

    // Section JSON embedded at compile time (same pattern as settings_ui.rs).
    static GENERAL_JSON: &str = include_str!("settings_ui_sections/general.json");
    static PROVIDERS_JSON: &str = include_str!("settings_ui_sections/providers.json");
    static MCP_JSON: &str = include_str!("settings_ui_sections/mcp.json");
    static CONTEXT_MGMT_JSON: &str = include_str!("settings_ui_sections/context_management.json");
    static MEMORY_JSON: &str = include_str!("settings_ui_sections/memory.json");
    static PROMPT_COMPOSER_JSON: &str = include_str!("settings_ui_sections/prompt_composer.json");

    fn load_section(src: &str) -> Value {
        serde_json::from_str(src).expect("static JSON should be valid")
    }

    fn general() -> Value {
        load_section(GENERAL_JSON)
    }
    fn providers() -> Value {
        load_section(PROVIDERS_JSON)
    }
    fn mcp() -> Value {
        load_section(MCP_JSON)
    }
    fn context_mgmt() -> Value {
        load_section(CONTEXT_MGMT_JSON)
    }
    fn memory() -> Value {
        load_section(MEMORY_JSON)
    }
    fn prompt_composer() -> Value {
        load_section(PROMPT_COMPOSER_JSON)
    }

    // ── Unit: field path validation ──────────────────────────────────────

    #[test]
    fn valid_top_level_paths() {
        let root = merged_schema();
        for path in &[
            "language",
            "active_provider",
            "default_model",
            "utility_small_model",
            "request_timeout_seconds",
            "show_advanced_request_options",
            "enable_developer_tools",
        ] {
            assert!(
                validate_field_path(path, &root, &root).is_ok(),
                "\"{path}\" should be valid in merged schema"
            );
        }
    }

    #[test]
    fn invalid_path_returns_error() {
        let root = merged_schema();
        assert!(validate_field_path("nonexistent", &root, &root).is_err());
    }

    #[test]
    fn valid_two_level_paths() {
        let root = merged_schema();
        for path in &[
            "memory.enabled",
            "memory.storage_dir",
            "context_management.dynamic_thresholds",
            "context_management.street_enabled",
            "mcp.startup_timeout_ms",
            "sub_agent.max_concurrent",
            "rag.chunk_size",
        ] {
            assert!(
                validate_field_path(path, &root, &root).is_ok(),
                "\"{path}\" should be valid in merged schema"
            );
        }
    }

    #[test]
    fn valid_provider_model_paths() {
        let root = merged_schema();
        let pm = def(&root, "ProviderModelConfig");
        for path in &[
            "name",
            "enabled",
            "api_protocol",
            "request.temperature",
            "request.top_p",
            "request.top_k",
            "request.max_output_tokens",
            "request.frequency_penalty",
            "request.presence_penalty",
            "request.reasoning_effort",
            "request.extra_body",
        ] {
            assert!(
                validate_field_path(path, &pm, &root).is_ok(),
                "\"{path}\" should be valid in ProviderModelConfig"
            );
        }
    }

    #[test]
    fn valid_mcp_server_paths() {
        let root = merged_schema();
        let ms = def(&root, "McpServerConfig");
        for path in &[
            "enabled",
            "transport",
            "command",
            "args",
            "env",
            "cwd",
            "use_global_stdio_env",
            "inherit_parent_env",
            "uri",
            "auth_header",
            "headers",
            "allow_stateless",
            "channel_buffer_capacity",
            "reinit_on_expired_session",
            "unfolded",
        ] {
            assert!(
                validate_field_path(path, &ms, &root).is_ok(),
                "\"{path}\" should be valid in McpServerConfig"
            );
        }
    }

    // ── Collection resolution ────────────────────────────────────────────

    #[test]
    fn resolve_providers_collection() {
        let root = merged_schema();

        match resolve_collection_item_schema("providers", &root, &root) {
            Ok(s) => {
                assert!(s.get("properties").is_some(), "should have properties");
                assert!(
                    s.get("properties").and_then(|p| p.get("kind")).is_some(),
                    "ProviderConfig should have 'kind'"
                );
            }
            Err(e) => panic!("resolve providers failed: {e}"),
        }
    }

    #[test]
    fn resolve_mcp_servers_collection() {
        let root = merged_schema();
        match resolve_collection_item_schema("mcp.servers", &root, &root) {
            Ok(s) => {
                assert!(
                    s.get("properties")
                        .and_then(|p| p.get("transport"))
                        .is_some(),
                    "McpServerConfig should have 'transport'"
                );
            }
            Err(e) => panic!("resolve mcp.servers failed: {e}"),
        }
    }

    // ── Integration: section validation ──────────────────────────────────

    #[test]
    fn general_section_valid() {
        let schema = merged_schema();
        assert!(validate_node(&general(), &schema, &schema, "").is_ok());
    }

    #[test]
    fn providers_section_valid() {
        let schema = merged_schema();
        assert!(validate_node(&providers(), &schema, &schema, "").is_ok());
    }

    #[test]
    fn mcp_section_valid() {
        let schema = merged_schema();
        assert!(validate_node(&mcp(), &schema, &schema, "").is_ok());
    }

    #[test]
    fn context_management_section_valid() {
        let schema = merged_schema();
        assert!(validate_node(&context_mgmt(), &schema, &schema, "").is_ok());
    }

    #[test]
    fn memory_section_valid() {
        let schema = merged_schema();
        assert!(validate_node(&memory(), &schema, &schema, "").is_ok());
    }

    #[test]
    fn prompt_composer_section_valid() {
        let schema = merged_schema();
        assert!(validate_node(&prompt_composer(), &schema, &schema, "").is_ok());
    }

    // ── Error cases ──────────────────────────────────────────────────────

    #[test]
    fn bad_path_rejected() {
        let root = merged_schema();
        let bad = json!({"id":"t","title":"T","icon":"T","order":0,"children":[
            {"kind":"field","id":"b","title":"B","path":"wrong","valueType":"string","control":"text"}
        ]});
        assert!(validate_node(&bad, &root, &root, "").is_err());
    }

    #[test]
    fn bad_nested_path_rejected() {
        let root = merged_schema();
        let bad = json!({"id":"t","title":"T","icon":"T","order":0,"children":[
            {"kind":"field","id":"b","title":"B","path":"memory.bad","valueType":"string","control":"text"}
        ]});
        assert!(validate_node(&bad, &root, &root, "").is_err());
    }

    #[test]
    fn bad_collection_child_rejected() {
        let root = merged_schema();
        // McpServerConfig doesn't have `nonexistent` field and does NOT have
        // additionalProperties: true (unlike ProviderConfig which has flattened maps)
        let bad = json!({"id":"t","title":"T","icon":"T","order":0,"children":[{
            "kind":"collection","id":"c","title":"C","path":"mcp.servers",
            "valueType":"object_collection","children":[
                {"kind":"field","id":"b","title":"B","path":"nonexistent","valueType":"string","control":"text"}
            ]
        }]});
        assert!(validate_node(&bad, &root, &root, "").is_err());
    }

    // ── Full suite ───────────────────────────────────────────────────────

    #[test]
    fn all_builtin_sections_valid() {
        let sections = vec![
            general(),
            providers(),
            mcp(),
            context_mgmt(),
            memory(),
            prompt_composer(),
        ];
        assert!(validate_settings_paths(&sections).is_ok());
    }
}
